sudo: false
language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6
env:
    - TOXENV=py,coverage-report

matrix:
    include:
        - python: 3.6
          env: TOXENV=py-babelex,coverage-report
        - python: 3.6
          env: TOXENV=py-no-babel,coverage-report
        - python: 3.6
          env: TOXENV=docs-html

install:
    - pip install tox

script:
    - tox

notifications:
    email: false
